### ISSUE TITLE
Can't make it work in argocd

### ISSUE THREAD

**Issue by christosnc** [redhat-cop/patch-operator#50]
Hello,

I am trying to install patch-operator using argocd. I already have prometheus and cert-manager installed, and I am installing using the helm chart.

All the resources install ok, but in the pod I keep getting two errors over and over again:
`... secret "webhook-server-cert" not found`
`... secret "patch-operator-certs" not found`

I tried installing both in the default namespace, as well as in a separate namespace, with the exact same results. I'm using v0.1.9 (latest at the moment)

Please help!

**Comment by davgordo** [comment]
Hi @christosnc, the Helm chart accepts a value called `enableCertManager` which is defaulted to false. Can you clarify whether you set the value to `true` when you executed the chart?

Also, if using `enableCertManager: true`. Are you able to find the Certificate resource called `serving-cert`? If you are able to locate the certificate resource, does it show a status?

**Comment by leotomas837** [comment]
Can you re-open this issue ? It does not work without cert-manager. Indeed, volumes are defined in the (manager.yaml)[https://github.com/redhat-cop/patch-operator/blob/main/config/helmchart/templates/manager.yaml] even when cert-manager is not defined therefore no secret are created.

```yaml
88      volumes:
89      - name: patch-operator-certs
90        secret:
91          defaultMode: 420
92          secretName: patch-operator-certs  
93      - name: webhook-server-cert
94        secret:
95          secretName: webhook-server-cert
96          defaultMode: 420     
```

Also, it would be nice if we could use our own cert, instead of having a self-signed issuer when enabling cert-manager.... Cert-manager itself strongly advised not to use self-signed issuer in production for example.
